woowacourse-teams/2023-trip-draw

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/RetrofitModule.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/retrofitAdapter/ResponseState.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/retrofitAdapter/ResponseStateCall.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/retrofitAdapter/ResponseStateCallAdapter.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/retrofitAdapter/ResponseStateCallAdapterFactory.kt, android/app/src/main/java/com/teamtripdraw/android/ui/MainActivity.kt, android/app/src/main/res/layout/activity_main.xml, android/gradle/libs.versions.toml, android/support/src/main/java/com/teamtripdraw/android/support/framework/data/Retrofits.kt
- closed #3 
- 레트로핏 기초세팅 및 오류처리 위한 callAdapter 생성
=> [feat] Http client 기초세팅 (#3)

backend/intellij-java-wooteco-style.xml, backend/src/main/java/dev/tripdraw/BackendApplication.java, backend/src/main/java/dev/tripdraw/config/JpaConfig.java, backend/src/main/java/dev/tripdraw/domain/BaseEntity.java, backend/src/main/java/dev/tripdraw/domain/Member.java, backend/src/main/java/dev/tripdraw/domain/Point.java, backend/src/main/java/dev/tripdraw/domain/Route.java, backend/src/main/java/dev/tripdraw/domain/Trip.java, backend/src/test/java/dev/tripdraw/domain/RouteTest.java, backend/src/test/java/dev/tripdraw/domain/TripTest.java
- close #8 
- 도메인 설계 및 생성
- Member
- Point
- Route (Point의 일급 컬렉션)
- Trip
- BaseEntity 작성하여, 각 도메인이 상속하도록 구현
- 몹 프로그래밍으로 구현 -> 리뷰 없이 머지하겠습니다.
=> [feat] 도메인 설계 및 생성 (#8)

backend/src/main/java/dev/tripdraw/exception/AuthException.java, backend/src/main/java/dev/tripdraw/exception/BadRequestException.java, backend/src/main/java/dev/tripdraw/exception/ExceptionCode.java, backend/src/main/java/dev/tripdraw/exception/ForbiddenException.java
- closed #17  
- 일부 CustomException 클래스 작성
- ExceptionCode Enum 작성
- 앞으로 예외는 직접 만들어서 사용하시면 됩니다
=> [feat] 예외 처리 기능 구현

android/app/src/main/res/values/colors.xml
=> [refactor] 디자인 컬러 변경 (#19)

backend/build.gradle, backend/src/main/java/dev/tripdraw/application/MemberService.java, backend/src/main/java/dev/tripdraw/config/AuthConfig.java, backend/src/main/java/dev/tripdraw/domain/member/MemberRepository.java, backend/src/main/java/dev/tripdraw/dto/LoginUser.java, backend/src/main/java/dev/tripdraw/dto/request/MemberCreateRequest.java, backend/src/main/java/dev/tripdraw/dto/response/MemberCreateResponse.java, backend/src/main/java/dev/tripdraw/exception/ExceptionCode.java, backend/src/main/java/dev/tripdraw/presentation/controller/MemberController.java, backend/src/main/java/dev/tripdraw/presentation/member/Auth.java, backend/src/main/java/dev/tripdraw/presentation/member/AuthArgumentResolver.java, backend/src/main/java/dev/tripdraw/presentation/member/AuthExtractor.java, backend/src/main/java/dev/tripdraw/presentation/member/BasicAuthorizationDecoder.java, backend/src/main/java/dev/tripdraw/presentation/member/LoginUser.java, backend/src/test/java/dev/tripdraw/application/MemberServiceTest.java, backend/src/test/java/dev/tripdraw/domain/member/MemberRepositoryTest.java, backend/src/test/java/dev/tripdraw/presentation/controller/MemberControllerTest.java, backend/src/test/java/dev/tripdraw/presentation/member/AuthExtractorTest.java, backend/src/test/java/dev/tripdraw/presentation/member/BasicAuthorizationDecoderTest.java, backend/src/test/resources/truncate.sql
- closed #9 
- 회원 인증 기능 구현
- 회원 가입 기능 구현
=> [feat] 회원 인증 및 가입 기능 구현 (#9)

backend/src/main/java/dev/tripdraw/application/TripService.java, backend/src/main/java/dev/tripdraw/domain/member/Member.java, backend/src/main/java/dev/tripdraw/domain/trip/Point.java, backend/src/main/java/dev/tripdraw/domain/trip/Trip.java, backend/src/main/java/dev/tripdraw/domain/trip/TripRepository.java, backend/src/main/java/dev/tripdraw/dto/request/PointCreateRequest.java, backend/src/main/java/dev/tripdraw/dto/response/PointCreateResponse.java, backend/src/main/java/dev/tripdraw/exception/ExceptionCode.java, backend/src/main/java/dev/tripdraw/presentation/controller/TripController.java, backend/src/test/java/dev/tripdraw/application/TripServiceTest.java, backend/src/test/java/dev/tripdraw/domain/trip/TripTest.java, backend/src/test/java/dev/tripdraw/dto/request/PointCreateRequestTest.java, backend/src/test/java/dev/tripdraw/presentation/controller/ControllerTest.java, backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
- closed #12 
- 위치 저장 기능 및 API 구현
- 인가 검증 로직
- JPA proxy 객체의 동등성 비교(Member.equals) 문제 발견 및 트러블 슈팅
- 제대로 한 거 맞는지 확인 부탁드립니다
=> [feat] 위치 저장 기능 구현 (#12)

backend/src/main/java/dev/tripdraw/dto/response/ExceptionResponse.java, backend/src/main/java/dev/tripdraw/presentation/controller/ControllerExceptionHandler.java
- closed #30
- ControllerAdvice 적용
=> [feat] ControllerAdvice 적용하여 예외 처리 (#30)

backend/build.gradle, backend/src/main/java/dev/tripdraw/application/MemberService.java, backend/src/main/java/dev/tripdraw/application/TripService.java, backend/src/main/java/dev/tripdraw/config/AuthConfig.java, backend/src/main/java/dev/tripdraw/domain/common/BaseEntity.java, backend/src/main/java/dev/tripdraw/domain/member/Member.java, backend/src/main/java/dev/tripdraw/domain/trip/Point.java, backend/src/main/java/dev/tripdraw/domain/trip/Route.java, backend/src/main/java/dev/tripdraw/domain/trip/Trip.java, backend/src/main/java/dev/tripdraw/domain/trip/TripName.java, backend/src/main/java/dev/tripdraw/dto/request/PointCreateRequest.java, backend/src/main/java/dev/tripdraw/dto/response/MemberCreateResponse.java, backend/src/main/java/dev/tripdraw/dto/response/PointCreateResponse.java, backend/src/main/java/dev/tripdraw/dto/response/TripCreateResponse.java, backend/src/main/java/dev/tripdraw/exception/common/BaseException.java, backend/src/main/java/dev/tripdraw/exception/common/GlobalExceptionHandler.java, backend/src/main/java/dev/tripdraw/presentation/controller/MemberController.java, backend/src/main/java/dev/tripdraw/presentation/controller/TripController.java, backend/src/main/java/dev/tripdraw/presentation/member/AuthArgumentResolver.java, backend/src/main/java/dev/tripdraw/presentation/member/AuthExtractor.java, backend/src/test/java/dev/tripdraw/application/MemberServiceTest.java, backend/src/test/java/dev/tripdraw/application/TripServiceTest.java, backend/src/test/java/dev/tripdraw/domain/member/MemberRepositoryTest.java, backend/src/test/java/dev/tripdraw/domain/trip/RouteTest.java, backend/src/test/java/dev/tripdraw/domain/trip/TripTest.java, backend/src/test/java/dev/tripdraw/dto/request/PointCreateRequestTest.java, backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
=> [refactor] 롬복 제거

backend/src/main/java/dev/tripdraw/application/MemberService.java, backend/src/main/java/dev/tripdraw/application/TripService.java, backend/src/main/java/dev/tripdraw/config/AuthConfig.java, backend/src/main/java/dev/tripdraw/domain/member/Member.java, backend/src/main/java/dev/tripdraw/domain/member/MemberRepository.java, backend/src/main/java/dev/tripdraw/domain/trip/Trip.java, backend/src/main/java/dev/tripdraw/dto/request/PointCreateRequest.java, backend/src/main/java/dev/tripdraw/dto/validation/NoWhiteSpace.java, backend/src/main/java/dev/tripdraw/exception/auth/AuthExceptionType.java, backend/src/main/java/dev/tripdraw/exception/common/ExceptionResponse.java, backend/src/main/java/dev/tripdraw/exception/member/MemberExceptionType.java, backend/src/main/java/dev/tripdraw/presentation/controller/TripController.java, backend/src/main/java/dev/tripdraw/presentation/member/Auth.java, backend/src/main/java/dev/tripdraw/presentation/member/AuthInterceptor.java, backend/src/test/java/dev/tripdraw/application/MemberServiceTest.java, backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
- closed #45 
- 인증을 위한 interceptor 구현했습니다.
- 사용하지 않는 상수와 메서드를 제거했습니다.
- TripService에서 MemberService에 대한 의존성을 제거했습니다.
=> [feat] 인증을 위한 Interceptor 구현 (#45)

.github/workflows/backend-dev-cd.yml
- closed #55
- 내부에 작성된 deploy.sh 파일을 실행하도록 수정한다.
=> [chore] 배포시 쉘 스크립트 사용하도록 수정 (#55)

.github/workflows/backend-dev-cd.yml, backend/src/main/java/dev/tripdraw/dto/auth/LoginUser.java
- close #53 
- LoginUser에 Hidden 어노테이션 적용
=> [fix] LoginUser에 Hidden 어노테이션 적용 (#53)

android/app/build.gradle.kts, android/build.gradle.kts, android/gradle/libs.versions.toml
- closed #57 
- 앱테스터 작동을 위해 Firebase 연동
=> [feat] 앱테스터 적용 / firebase 라이브러리 추가 (#57)

backend/src/main/java/dev/tripdraw/config/swagger/SwaggerConfig.java
- closed #77 
Swagger 설정을 일관성있게 변경했습니다.
커밋에 이슈 번호를 안적었네요.. 다음부턴 적도록 하겠습니다 😢
=> [refactor] Swagger 설정 리팩터링 (#77)

backend/src/main/java/dev/tripdraw/domain/common/BaseEntity.java, backend/src/main/java/dev/tripdraw/domain/member/Member.java, backend/src/main/java/dev/tripdraw/domain/post/Post.java, backend/src/main/java/dev/tripdraw/domain/trip/Point.java, backend/src/main/java/dev/tripdraw/domain/trip/Trip.java
- closed #82 
id 필드를 BaseEntity에서 각각의 클래스로 위치 변경했습니다.
=> [refactor] id 필드를 BaseEntity에서 각각의 클래스로 위치 변경 (#82)

backend/src/main/java/dev/tripdraw/config/swagger/SwaggerAuthorizationRequired.java, backend/src/main/java/dev/tripdraw/config/swagger/SwaggerConfig.java, backend/src/main/java/dev/tripdraw/config/swagger/SwaggerLoginRequired.java, backend/src/main/java/dev/tripdraw/dto/member/MemberCreateRequest.java, backend/src/main/java/dev/tripdraw/dto/member/MemberResponse.java, backend/src/main/java/dev/tripdraw/dto/trip/PointCreateRequest.java, backend/src/main/java/dev/tripdraw/dto/trip/PointResponse.java, backend/src/main/java/dev/tripdraw/dto/trip/TripResponse.java, backend/src/main/java/dev/tripdraw/exception/auth/AuthExceptionType.java, backend/src/main/java/dev/tripdraw/presentation/controller/MemberController.java, backend/src/main/java/dev/tripdraw/presentation/controller/TripController.java, backend/src/main/java/dev/tripdraw/presentation/member/AuthExtractor.java, backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java, backend/src/test/java/dev/tripdraw/presentation/member/AuthExtractorTest.java
- closed #94 
- Schema 설명 추가
- 기본 값 설정
- Authorization Bearer 설정
- Response 설명 200 -> 201로 정정
- 인증 방식 Bearer를 앞에 붙이도록 수정
=> [fix] Authorization 헤더 형식 변경 및 Swagger 호출 안되는 버그 수정 (#94)

android/app/src/main/java/com/teamtripdraw/android/di/RetrofitContainer.kt
=> [fIx] 서버 인증헤더 형식 변경 대응 인터셉터 작업 (#94대응) (#100)

.github/workflows/backend-prod-cd.yml, .github/workflows/backend-prod-ci.yml
** 몹 프로그래밍으로 진행한 인프라 관련 이슈로, 리뷰 없이 머지하겠습니다.
- closed #123
프로덕션 서버에 CI/CD 적용
=> [chore] 프로덕션 서버 CI/CD 적용 (#123)

.github/workflows/backend-prod-cd.yml
** 인프라 관련 이슈이며, 몹 프로그래밍으로 진행 -> 리뷰 없이 머지하겠습니다.
- closed #127 
- github runners 재설치
- runs-on에 등록하는 lable 수정
=> [chore] github runners 및 스크립트 재설정 (#127)

android/app/src/main/java/com/teamtripdraw/android/TripDrawApplication.kt, android/app/src/main/java/com/teamtripdraw/android/data/dataSource/nicknameSetup/NicknameSetupDataSource.kt, android/app/src/main/java/com/teamtripdraw/android/data/dataSource/nicknameSetup/RemoteNicknameSetupDataSourceImpl.kt, android/app/src/main/java/com/teamtripdraw/android/data/dataSource/trip/RemoteTripDataSourceImpl.kt, android/app/src/main/java/com/teamtripdraw/android/data/dataSource/trip/TripDataSource.kt, android/app/src/main/java/com/teamtripdraw/android/data/repository/NicknameSetupRepositoryImpl.kt, android/app/src/main/java/com/teamtripdraw/android/data/repository/TripRepositoryImpl.kt, android/app/src/main/java/com/teamtripdraw/android/di/RemoteDataSourceContainer.kt, android/app/src/main/java/com/teamtripdraw/android/di/RepositoryContainer.kt
- closed #131
- RemoteDataSource 등 DataLayer 구조에대한 컨벤션 변경으로 인한 코드 수정
=> [refactor] 전체 / Data layer 컨벤션 변경으로 인한 코드 수정 (#131)

android/app/src/main/java/com/teamtripdraw/android/data/repository/PostRepositoryImpl.kt, android/app/src/main/java/com/teamtripdraw/android/di/RemoteDataSourceContainer.kt, android/app/src/main/java/com/teamtripdraw/android/di/RepositoryContainer.kt, android/app/src/main/java/com/teamtripdraw/android/di/ServiceContainer.kt, android/app/src/main/java/com/teamtripdraw/android/ui/common/TripDrawViewModelFactory.kt
=> [refactor] 감상 서버 통신 관련 기초 세팅 / Container 추가 (#102)

.gitignore
* 인프라 관련 세팅으로 리뷰없이 머지하겠습니다
- closed #143
=> [chore] 이미지 관련 yml 설정을 변경한다 (#143)

android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeFragment.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/recordingPoint/RecordingPointService.kt
- closed #134 
- 위치정보 주기적 업데이트
- 마지막 위치정보 가져오기
- tripId를 전달하여 service와 AlarmManager 시작시키기
- 알림권한 받기
=> [feat] 메인 화면_홈 / 위치정보 가져오는기능 설정 (#134)

backend/src/main/java/dev/tripdraw/application/PostService.java, backend/src/main/java/dev/tripdraw/application/TripService.java, backend/src/main/java/dev/tripdraw/domain/post/Post.java, backend/src/main/java/dev/tripdraw/dto/post/PostResponse.java, backend/src/main/java/dev/tripdraw/exception/post/PostException.java, backend/src/main/java/dev/tripdraw/exception/post/PostExceptionType.java, backend/src/main/java/dev/tripdraw/presentation/controller/PostController.java, backend/src/main/java/dev/tripdraw/presentation/controller/TripController.java, backend/src/test/java/dev/tripdraw/application/PostServiceTest.java, backend/src/test/java/dev/tripdraw/application/TripServiceTest.java, backend/src/test/java/dev/tripdraw/domain/post/PostTest.java, backend/src/test/java/dev/tripdraw/dto/post/PostResponseAndPointCreateRequestTest.java, backend/src/test/java/dev/tripdraw/presentation/controller/MemberControllerTest.java, backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java, backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
- closed #152 
- 점 조회 api 추가했습니다.
=> [feat] 점 조회 api 추가 (#152)

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/teamtripdraw/android/ui/common/TripDrawViewModelFactory.kt, android/app/src/main/java/com/teamtripdraw/android/ui/common/animation/ObjectAnimators.kt, android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/HomeBindingAdapter.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeFragment.kt, android/app/src/main/res/drawable/ic_fab_plus.xml, android/app/src/main/res/drawable/ic_fab_plus_rotate_45.xml, android/app/src/main/res/drawable/ic_marker_mode.xml, android/app/src/main/res/drawable/ic_post_list.xml, android/app/src/main/res/drawable/ic_write_post.xml, android/app/src/main/res/layout/fragment_home.xml, android/app/src/main/res/values/strings.xml
- closed #167 
- 여행중 상태 버튼생성 및 visibility 처리
=> [feat] 메인 화면_홈 / 여행중 모드 버튼생성 (#167)

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/teamtripdraw/android/data/dataSource/point/PointDataSource.kt, android/app/src/main/java/com/teamtripdraw/android/data/dataSource/point/RemotePointDataSourceImpl.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/mapper/PostDtoMapper.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/GetPointResponse.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/service/GetPointService.kt, android/app/src/main/java/com/teamtripdraw/android/data/model/mapper/PointMapper.kt, android/app/src/main/java/com/teamtripdraw/android/data/model/mapper/PostDataMapper.kt, android/app/src/main/java/com/teamtripdraw/android/data/repository/PointRepositoryImpl.kt, android/app/src/main/java/com/teamtripdraw/android/di/RemoteDataSourceContainer.kt, android/app/src/main/java/com/teamtripdraw/android/di/ServiceContainer.kt, android/app/src/main/java/com/teamtripdraw/android/ui/common/TripDrawViewModelFactory.kt, android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/PointBindingAdapter.kt, android/app/src/main/java/com/teamtripdraw/android/ui/postWriting/PostWritingActivity.kt, android/app/src/main/java/com/teamtripdraw/android/ui/postWriting/PostWritingViewModel.kt, android/app/src/main/res/layout/activity_post_writing.xml, android/domain/src/main/java/com/teamtripdraw/android/domain/model/point/LatLngPoint.kt, android/domain/src/main/java/com/teamtripdraw/android/domain/repository/PointRepository.kt
- #97 
- repository를 통한 여행 정보 조회 기능 추가
=> [feat] 감상 기록 / repository를 통한 여행 정보 조회 기능 추가 (#97)

backend/src/main/java/dev/tripdraw/application/draw/RouteImageUploader.java, backend/src/main/java/dev/tripdraw/dto/trip/TripResponse.java
=> [fix] 이미지 저장 기능 수정 및 API 명세에 맞게 필드 변경 (#172)

backend/src/main/java/dev/tripdraw/application/draw/RouteImageUploader.java, backend/src/test/java/dev/tripdraw/application/draw/RouteImageUploaderTest.java
- closed #174 
- 이미지 저장 기능 URL 수정
=> [fix] 이미지 저장 기능 URL 수정 (#174)

backend/src/main/java/dev/tripdraw/application/draw/RouteImageUploader.java, backend/src/test/java/dev/tripdraw/application/draw/RouteImageUploaderTest.java
- closed #178 
-  경로 이미지 저장 경로 수정
=> [fix] 경로 이미지 저장 경로 수정 (#178)

backend/src/main/java/dev/tripdraw/application/draw/RouteImageUploader.java, backend/src/test/java/dev/tripdraw/application/draw/RouteImageUploaderTest.java
=> [fix] 경로 이미지 저장 경로 수정 #180

backend/src/main/java/dev/tripdraw/domain/draw/RouteImageDrawer.java, backend/src/test/java/dev/tripdraw/domain/draw/RouteImageDrawerTest.java
- closed #184 
- 위치점을 파란색, 경로선을 회색으로 변경했습니다.
=> [refactor] 경로 이미지의 경로색 및 위치 점 색상 수정 #184

android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt, android/app/src/main/res/layout/activity_post_detail.xml
- closed #182 
- 통신이 되기 전에 이미지 주소가 null이 되는 문제를 수정
=> [refactor] 감상 상세보기 / 이미지 null 처리 수정 (#182)

android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeFragment.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/post/viewer/PostViewerActivity.kt, android/app/src/main/java/com/teamtripdraw/android/ui/post/viewer/PostViewerViewModel.kt, android/app/src/main/res/layout/fragment_home.xml, android/app/src/main/res/layout/item_post_viewer.xml, android/app/src/test/java/com/teamtripdraw/android/ui/post/viewer/PostViewerViewModelTest.kt
- closed #171 
- 메인 화면에서 감상 목록으로 가는 화면을 이어준다.
=> [feat] 메인 화면과 감상 목록 연결 (#171)

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/teamtripdraw/android/data/dataSource/post/PostDataSource.kt, android/app/src/main/java/com/teamtripdraw/android/data/dataSource/post/remote/RemotePostDataSourceImpl.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/service/PostService.kt, android/app/src/main/java/com/teamtripdraw/android/data/repository/PostRepositoryImpl.kt, android/app/src/main/java/com/teamtripdraw/android/ui/postWriting/PostWritingActivity.kt, android/app/src/main/java/com/teamtripdraw/android/ui/postWriting/PostWritingViewModel.kt, android/app/src/main/res/layout/activity_post_writing.xml, android/app/src/test/java/com/teamtripdraw/android/ui/postWriting/PostWritingViewModelTest.kt, android/domain/src/main/java/com/teamtripdraw/android/domain/model/post/PrePost.kt, android/domain/src/main/java/com/teamtripdraw/android/domain/repository/PostRepository.kt, android/support/src/main/java/com/teamtripdraw/android/support/framework/presentation/extensions/UriExtensions.kt
- closed #97 
- 갤러리에서 이미지를 가져와 추가하는 기능
=> [feat] 감상 기록 / 갤러리 이미지 기능 추가 (#97)

android/app/src/main/java/com/teamtripdraw/android/ui/common/TripDrawViewModelFactory.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeFragment.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/recordingPoint/RecordingPointService.kt, android/support/src/main/AndroidManifest.xml, android/support/src/main/java/com/teamtripdraw/android/support/framework/presentation/Locations.kt
- closed #191
- 감상작성 액티비티 이동로직을 작성한다.
=> [feat] 메인 화면_홈 / PostWritingActivity 이동로직 작성 (#191)

android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/NaverMapBindingAdapter.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeFragment.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/recordingPoint/RecordingPointService.kt, android/app/src/main/res/layout/fragment_home.xml
- closed #193 
- RecordingPointService를 homeFragment에 바인딩하여 위치가 업데이트될 때마다 화면에 마커를 그려주도록 설정한다.
=> [feat] 메인 화면_홈 / RecordingPointService homeFragment 에 바인딩 작업 (#193)

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/teamtripdraw/android/TripDrawApplication.kt
=> [feat] 다크모드,가로모드 막기 (#202)

android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/NaverMapBindingAdapter.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/UiMarkerInfo.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/UiRoute.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/mapper/PointUiMapper.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/mapper/TripUiMapper.kt, android/app/src/main/res/layout/fragment_home.xml, android/domain/src/main/java/com/teamtripdraw/android/domain/model/point/Route.kt
- closed #200 
- MVVM아키텍쳐에 맞춰 뷰모델의 역할을 고려하여 변경의 전파가 적어지도록 변경한다.
- 레이어드 아키텍쳐의 장점을 얻기위하여 각 역할을 고려하여 로직의 위치를 이동한다.
=> [refactor] 메인 화면_홈 / ui 모델과 domain 모델의 역할에 맞게 로직 위치이동 및 뷰모델 변경 및 테스트 작성 (#200)

android/app/src/main/java/com/teamtripdraw/android/ui/postWriting/PostWritingActivity.kt
- closed #211 
- activity의 context가 필요한 객체를 activity 객체 생성 시점에 초기화하는 문제가 있습니다.
- 어제 밤에 정신이 없어 실수했습니다 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 🙇🏻‍♀️ 
- 머지 하게 해주세요... 부탁드립니다...
=> [fix] 감상 기록 / 주소 표기 방식 수정 (#211) 

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/teamtripdraw/android/ui/postWriting/PostWritingActivity.kt, android/app/src/main/java/com/teamtripdraw/android/ui/postWriting/PostWritingViewModel.kt, android/app/src/main/res/layout/activity_post_writing.xml, android/support/src/main/java/com/teamtripdraw/android/support/framework/presentation/extensions/UriExtensions.kt
- closed #219 
- 안드로이드 하위 버전에서 이미지를 선택하고자할 때 anr이 발생하는 문제 수정
=> [fix] 감상 기록 / sdk 버전 12 이하에서 PhotoPicker로부터 가져온 이미지를 File로 만들 때 ANR 해결 (#219)

android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/teamtripdraw/android/ui/common/TripDrawViewModelFactory.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeFragment.kt, android/app/src/main/java/com/teamtripdraw/android/ui/post/writing/PostWritingActivity.kt, android/app/src/main/java/com/teamtripdraw/android/ui/post/writing/PostWritingViewModel.kt, android/app/src/main/res/layout/activity_post_writing.xml, android/app/src/test/java/com/teamtripdraw/android/ui/home/HomeViewModelTest.kt, android/app/src/test/java/com/teamtripdraw/android/ui/post/writing/PostWritingViewModelTest.kt
=> [refactor] 감상 기록 / 패키지 변경 및 테스트 수정 (#215)

backend/src/main/java/dev/tripdraw/application/MemberService.java, backend/src/main/java/dev/tripdraw/domain/member/Member.java, backend/src/main/java/dev/tripdraw/presentation/controller/MemberController.java, backend/src/main/resources/db/migration/h2/V5__addMemberDeletion.sql, backend/src/main/resources/db/migration/mysql/V5__addMemberDeletion.sql, backend/src/test/java/dev/tripdraw/application/MemberServiceTest.java, backend/src/test/java/dev/tripdraw/domain/member/MemberRepositoryTest.java, backend/src/test/java/dev/tripdraw/domain/member/MemberTest.java, backend/src/test/java/dev/tripdraw/presentation/controller/MemberControllerTest.java
* 내일 재택근무 이슈로 인해, 빠르게 머지하겠습니다.
- closed #240 
- 회원 탈퇴 기능 추가
- 회원 조회 기능 수정
- JPA @Where, @SQLDelete 를 활용해보았습니다.
=> [feat] 회원 탈퇴 기능 (#240)

android/app/src/main/java/com/teamtripdraw/android/ui/common/TripDrawViewModelFactory.kt, android/app/src/main/java/com/teamtripdraw/android/ui/history/tripDetail/TripDetailActivity.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/markerSelectedBottomSheet/MarkerSelectedBottomSheet.kt, android/app/src/main/res/layout/activity_trip_detail.xml
- closed #244 
- 각 팀원의 코드 업데이트 시간순서에 의한 오류를 수정한다.
=> [fix] 여행 히스토리 / 코드 업데이트 시간순서에 의한 오류 수정 (#244)

android/app/src/main/java/com/teamtripdraw/android/data/repository/TripRepositoryImpl.kt, android/app/src/main/java/com/teamtripdraw/android/ui/common/dialog/SetTripTitleDialog.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeFragment.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/recordingPoint/RecordingPointAlarmManager.kt, android/app/src/main/res/layout/fragment_home.xml, android/domain/src/main/java/com/teamtripdraw/android/domain/repository/TripRepository.kt
- closed #217 
- 여행종료 기능을 구현한다
=> [feat] 메인 화면_홈 / 여행 종료 기능 (#217)

android/.gitignore, android/app/build.gradle.kts, android/app/src/main/AndroidManifest.xml
- closed #248 
- Relase, Dev버전 분리
=> [feat] Release,Dev버전 분리 (#248)

android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeFragment.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeViewModel.kt
- closed #259 
- 머지 과정에서 일어난 충돌로 생긴 오류 해결
=> [fix] 충돌 오류 해결 (#259)

android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeFragment.kt
- closed #263 
- 바인드된 서비스 여행종료시 unbind됨으로 onDestory시 bind중인지 확인하는 조건추가
=> [fix] 메인 화면_홈 / 서비스 unbind 조건 변경 (#263)

backend/build.gradle, backend/src/main/java/dev/tripdraw/config/AuthConfig.java, backend/src/main/resources/application-local.yml
- closed #272
- actuator 설정 했습니다.
=> [chore] actuator, prometheus 설정 추가 (#272)

android/app/src/main/java/com/teamtripdraw/android/data/dataSource/signUp/RemoteSignUpDataSourceImpl.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/mapper/UserDtoMapper.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/GetUserInfoResponse.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/LoginResponse.kt, android/app/src/main/java/com/teamtripdraw/android/data/model/DataUserInfo.kt, android/app/src/main/java/com/teamtripdraw/android/data/model/mapper/UserMapeer.kt, android/app/src/main/java/com/teamtripdraw/android/ui/login/LoginActivity.kt, android/app/src/main/java/com/teamtripdraw/android/ui/login/LoginViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/signUp/NicknameSetupViewModel.kt, android/app/src/test/java/com/teamtripdraw/android/ui/signUp/NicknameSetupViewModelTest.kt, android/domain/src/main/java/com/teamtripdraw/android/domain/exception/NicknameSetupException.kt, android/domain/src/main/java/com/teamtripdraw/android/domain/model/user/UserInfo.kt
- #277 에서 코드리뷰 반영한걸 실수로 푸시 안하고 머지했습니다.
- 그래서 추가된 풀리퀘입니다.
-
=> [feat] 소셜로그인 / 카카오 로그인 작업 코드리뷰 반영 (#277)

android/app/proguard-rules.pro
=> [feat] 난독화 코드 추가 (#297)

.github/workflows/backend-dev-cd.yml, .github/workflows/backend-prod-cd.yml
=> [chore] CD 설정 변경 (#325)

.github/workflows/backend-dev-cd.yml
- github actions self hosted runner를 위한 설정입니다.
=> [chore] dev cd 스크립트 수정

android/app/src/main/java/com/teamtripdraw/android/ui/common/dialog/SetTripTitleDialogViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/history/HistoryViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/history/detail/HistoryDetailViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/history/tripDetail/TripDetailViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/post/detail/PostDetailViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/post/viewer/PostViewerActivity.kt, android/app/src/main/java/com/teamtripdraw/android/ui/post/viewer/PostViewerViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/signUp/NicknameSetupViewModel.kt
=> [refactor] 오류 상황에 로그찍기 (#332)

android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/recordingPoint/RecordingPointService.kt, android/app/src/main/java/com/teamtripdraw/android/ui/login/LoginViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/myPage/MyPageViewModel.kt, android/support/src/main/java/com/teamtripdraw/android/support/framework/presentation/log/LogUtil.kt
- closed #353 
- 로그 유틸로 기존 log todo 변경
=> [feat] logUtil 로 Log 변경 (#353)

android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/request/PatchPostRequest.kt, android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/CommonBindingAdapter.kt, android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/ImageBindingAdapter.kt, android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/PostWritingBindingAdapter.kt, android/app/src/main/java/com/teamtripdraw/android/ui/post/writing/PostWritingViewModel.kt, android/app/src/main/res/drawable/ic_image_delete.xml, android/app/src/main/res/layout/activity_post_writing.xml, android/app/src/test/java/com/teamtripdraw/android/ui/post/writing/PostWritingViewModelTest.kt, android/support/src/main/java/com/teamtripdraw/android/support/framework/presentation/extensions/UriExtensions.kt
=> [feat] 감상 기록 / 이미지 삭제 (#304)

backend/src/main/java/dev/tripdraw/post/dto/PostSearchResponse.java, backend/src/main/java/dev/tripdraw/trip/dto/TripSearchResponse.java, backend/src/main/java/dev/tripdraw/trip/query/TripCustomRepositoryImpl.java
- closed #381 
- 여행 조회 시 중복되어 조회되는 문제를 해결합니다.
- distinct() 추가
=> [fix] 여행 중복 조회 제거 (#381)

android/app/src/main/java/com/teamtripdraw/android/ui/common/dialog/SetTripTitleDialog.kt, android/app/src/main/java/com/teamtripdraw/android/ui/common/dialog/SetTripTitleDialogViewModel.kt, android/app/src/main/res/layout/activity_history_detail.xml, android/app/src/main/res/layout/activity_my_history.xml, android/app/src/main/res/layout/activity_trip_detail.xml
- closed #410 
- 여행 저장 시 터지는 버그 잡기
- 공유 아이콘 제거
=> [refactor] 버그 수정 및 불필요 아이콘 제거 (#410)

android/app/src/main/java/com/teamtripdraw/android/ui/login/LoginActivity.kt, android/app/src/main/java/com/teamtripdraw/android/ui/myPage/MyPageFragment.kt
- closed #420 
오류사항 수정 -> 이슈 참고
=> [fix] 로그아웃시 flag 전달에 따라 나는 오류 수정 (#420)

android/app/build.gradle.kts, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/teamtripdraw/android/data/dataSource/geocoding/RemoteGeocodingDataSourceImpl.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/mapper/GeocodingMapper.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/retrofitAdapter/ServerType.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/retrofitAdapter/responseState/enqueueActions/TripDrawEnqueueActions.kt, android/app/src/main/java/com/teamtripdraw/android/data/model/DataReverseGeocoding.kt, android/app/src/main/java/com/teamtripdraw/android/data/repository/GeocodingRepositoryImpl.kt, android/app/src/main/java/com/teamtripdraw/android/di/RetrofitModule.kt
- closed #335 
- 해당 PR에서 빠진 부분이 있어 다시 PR 드립니다!!! 🙇🏻‍♀️🙇🏻‍♀️🙇🏻‍♀️   
https://github.com/woowacourse-teams/2023-trip-draw/pull/390
- 번거로우시겠지만 두 PR 모두 살펴봐주시면 감사하겠습니다!
=> [refactor] android geocoder를 naver ReverseGeocoding으로 변경하기 (#335)

android/app/src/main/java/com/teamtripdraw/android/di/LocalPreferenceModule.kt, android/app/src/main/res/xml/backup_rules.xml
- closed #424
- EncryptedSharedPreference 백업관련 오류사항 수정하였습니다. 자세한 내용은 이슈를 참고하세요
=> [fix] EncryptedSharedPreference 관련 오류사항 (#424)

android/app/proguard-rules.pro
=> [fix] release 1.1.0에서 발생하는 주소 변환시 ANR 발생 문제 해결 (#446)

android/app/src/main/java/com/teamtripdraw/android/ui/home/recordingPoint/RecordingPointAlarmManager.kt
- closed #448 
- 경로 기록시간 5분으로 단축
=> [feat] 경로 기록시간 5분으로 단축 (#448)

backend/src/main/java/dev/tripdraw/trip/application/PointService.java, backend/src/main/java/dev/tripdraw/trip/application/TripService.java, backend/src/main/java/dev/tripdraw/trip/presentation/PointController.java, backend/src/main/java/dev/tripdraw/trip/presentation/TripController.java, backend/src/test/java/dev/tripdraw/trip/application/PointServiceTest.java, backend/src/test/java/dev/tripdraw/trip/application/TripServiceTest.java, backend/src/test/java/dev/tripdraw/trip/presentation/PointControllerTest.java, backend/src/test/java/dev/tripdraw/trip/presentation/TripControllerTest.java
- closed #440 
- Point Controller와 Service를 TripController, TripService에서 분리하였습니다!
=> [refactor] Point와 Trip Controller, Service 분리

android/support/src/main/java/com/teamtripdraw/android/support/framework/presentation/log/tripDrawLogUtil/TripDrawLogUtil.kt
- closed #456 
- 기존 error body 수집 Retrofit의 responseBody 형태로 수집되던것 String 형태로 수집되게 변경
=> [fix] sentry failure error body context 이상하게 수집되는 부분 수정 (#456)

backend/src/main/java/dev/tripdraw/common/config/AuthConfig.java, backend/src/main/java/dev/tripdraw/common/profile/presentation/ProfileController.java, backend/src/test/java/dev/tripdraw/common/profile/presentation/ProfileControllerTest.java
- closed #432 
- 무중단 배포 구현을 위한 현재 프로파일 확인 API를 구현했습니다.
=> [feat] 무중단 배포 구현 (#432)

backend/src/main/resources/logback-spring.xml
- closed #432 
- logback 설정파일 변경
=> [refactor] logback.xml 설정 변경 (#432)

backend/src/main/java/dev/tripdraw/admin/config/AdminConfig.java, backend/src/main/java/dev/tripdraw/admin/presentation/AdminInterceptor.java, backend/src/main/java/dev/tripdraw/post/application/PostService.java, backend/src/main/java/dev/tripdraw/trip/application/TripService.java, backend/src/main/java/dev/tripdraw/trip/domain/Point.java, backend/src/main/java/dev/tripdraw/trip/presentation/TripController.java, backend/src/test/java/dev/tripdraw/admin/presentation/AdminControllerTest.java, backend/src/test/java/dev/tripdraw/post/application/PostServiceTest.java, backend/src/test/java/dev/tripdraw/trip/application/TripServiceTest.java, backend/src/test/java/dev/tripdraw/trip/domain/PointTest.java
- closed #477 #478 #479 
- 인터셉터 정상 작동하지 않는 버그 수정
- hasPost false로 변경하는 부분 수정
- 여행 단일 조회 자기 자신 인증하는 부분 제거
=> [fix] 백엔드 버그 수정 (#477, #478, #479)

android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/mapper/PostDtoMapper.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/mapper/TripDtoMapper.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/GetAllPostsResponse.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/GetAllTripsResponse.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/GetTripInfoResponse.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/GetTripPostListResponse.kt, android/app/src/main/java/com/teamtripdraw/android/data/model/DataPost.kt, android/app/src/main/java/com/teamtripdraw/android/data/model/DataPostOfAll.kt, android/app/src/main/java/com/teamtripdraw/android/data/model/DataTrip.kt, android/app/src/main/java/com/teamtripdraw/android/data/model/DataTripOfAll.kt, android/app/src/main/java/com/teamtripdraw/android/data/model/mapper/PostDataMapper.kt, android/app/src/main/java/com/teamtripdraw/android/data/model/mapper/TripMapper.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/UiPostDetail.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/UiPostOfAll.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/UiTripOfAll.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/mapper/PostUiMapper.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/mapper/TripUiMapper.kt, android/domain/src/main/java/com/teamtripdraw/android/domain/model/post/Post.kt, android/domain/src/main/java/com/teamtripdraw/android/domain/model/post/PostOfAll.kt, android/domain/src/main/java/com/teamtripdraw/android/domain/model/trip/Trip.kt, android/domain/src/main/java/com/teamtripdraw/android/domain/model/trip/TripOfAll.kt
- closed #484 
- 여행, 감상에 대한 사용자 정보 추가에 따른 dto 수정
- isMine과 authorNickname 추가됨
=> [refactor] 여행, 감상에 대한 사용자 정보 추가에 따른 dto 수정 (#484)

backend/src/main/java/dev/tripdraw/admin/application/AdminService.java, backend/src/main/java/dev/tripdraw/admin/dto/AdminStatsResponse.java, backend/src/main/java/dev/tripdraw/admin/presentation/AdminController.java, backend/src/main/java/dev/tripdraw/trip/application/TripService.java, backend/src/main/java/dev/tripdraw/trip/presentation/TripController.java, backend/src/test/java/dev/tripdraw/admin/application/AdminServiceTest.java, backend/src/test/java/dev/tripdraw/admin/presentation/AdminControllerTest.java, backend/src/test/java/dev/tripdraw/trip/application/TripServiceTest.java
- closed #491 #494
- 모든 여행 조회에서 isMine 필드가 무조건 true로 반환되는 버그 수정했습니다!
- 어드민 대시보드를 위한 api 추가 (#494)
=> [fix] 모든 여행 조회에서 isMine 필드가 무조건 true로 반환되는 버그 수정 및 API 추가 (#491, #494)

android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/mapper/PointDtoMapper.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/GetPointPostResponse.kt
=> [fix] 감상에 사용자 정보 추가에 따른 dto 수정 (#502)

android/app/src/main/java/com/teamtripdraw/android/ui/allTrips/AllTripsAdapter.kt, android/app/src/main/java/com/teamtripdraw/android/ui/allTrips/AllTripsFragment.kt, android/app/src/main/java/com/teamtripdraw/android/ui/allTrips/AllTripsViewHolder.kt, android/app/src/main/java/com/teamtripdraw/android/ui/allTrips/AllTripsViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/allTrips/UiAllTripItem.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/allTrips/UiAllTripLoadingItem.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/allTrips/UiAllTrips.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/allTrips/UiTripOfAll.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/mapper/TripUiMapper.kt, android/app/src/main/res/layout/item_all_trips.xml
- closed #495 
- 모두의 여행 화면 무한스크롤 적용하였습니다.
- 아쉽지만 리펙은 조금만 미루겠습니다...🥲
=> [feat] 전체 여행 / 무한스크롤 (#495)

backend/src/main/java/dev/tripdraw/post/dto/v1/PostResponseV1.java, backend/src/main/java/dev/tripdraw/post/dto/v1/PostSearchResponseV1.java, backend/src/main/java/dev/tripdraw/post/dto/v1/PostsResponseV1.java, backend/src/main/java/dev/tripdraw/post/dto/v1/PostsSearchResponseV1.java, backend/src/main/java/dev/tripdraw/post/presentation/PostController.java, backend/src/main/java/dev/tripdraw/post/presentation/PostV1Controller.java, backend/src/main/java/dev/tripdraw/trip/dto/v1/TripResponseV1.java, backend/src/main/java/dev/tripdraw/trip/dto/v1/TripSearchResponseV1.java, backend/src/main/java/dev/tripdraw/trip/dto/v1/TripsSearchResponseV1.java, backend/src/main/java/dev/tripdraw/trip/presentation/TripController.java, backend/src/main/java/dev/tripdraw/trip/presentation/TripControllerV1.java, backend/src/test/java/dev/tripdraw/post/presentation/PostControllerTest.java, backend/src/test/java/dev/tripdraw/post/presentation/PostV1ControllerTest.java, backend/src/test/java/dev/tripdraw/trip/presentation/TripControllerV1Test.java
- closed #515 
- API 버저닝을 적용했습니다.
=> [feat] API 버저닝 적용 (#515)

android/app/build.gradle.kts, android/app/src/main/java/com/teamtripdraw/android/di/RetrofitModule.kt, android/app/src/main/java/com/teamtripdraw/android/di/qualifier/Qualifiers.kt
- closed #516 
- api 버저닝 기능 신설로 관련 대응(이슈참고)
=> [feat] api 버저닝 대응하여 api 버전 관련 헤더 추가 (#516)

android/app/src/main/java/com/teamtripdraw/android/ui/allTrips/AllTripsViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/IconBindingAdapter.kt, android/app/src/main/java/com/teamtripdraw/android/ui/history/tripDetail/TripDetailActivity.kt, android/app/src/main/java/com/teamtripdraw/android/ui/history/tripDetail/TripDetailViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/markerSelectedBottomSheet/MarkerSelectedBottomSheet.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/markerSelectedBottomSheet/MarkerSelectedViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/model/UiPreviewTrip.kt, android/app/src/main/res/layout/activity_history_detail.xml, android/app/src/main/res/layout/activity_post_detail.xml, android/app/src/main/res/layout/bottom_sheet_marker_selected.xml
- closed #490 
- 자신의 여행, 감상이 아니라면 삭제와 수정 불가능
=> [refactor] 여행 상세 화면, 감상 상세 화면 / 자신의 여행, 감상이 아니라면 삭제와 수정 불가능 (#490)

android/app/src/main/java/com/teamtripdraw/android/data/dataSource/post/PostDataSource.kt, android/app/src/main/java/com/teamtripdraw/android/data/dataSource/post/remote/RemotePostDataSourceImpl.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/request/CreateCurrentPointPostRequest.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/dto/response/CreateCurrentPointPostResponse.kt, android/app/src/main/java/com/teamtripdraw/android/data/httpClient/service/CreateCurrentPointPostService.kt, android/app/src/main/java/com/teamtripdraw/android/data/repository/PostRepositoryImpl.kt, android/app/src/main/java/com/teamtripdraw/android/di/ServiceModule.kt, android/app/src/main/java/com/teamtripdraw/android/ui/post/writing/PostWritingActivity.kt, android/app/src/main/java/com/teamtripdraw/android/ui/post/writing/PostWritingViewModel.kt, android/app/src/main/java/com/teamtripdraw/android/ui/post/writing/WritingMode.kt, android/app/src/test/java/com/teamtripdraw/android/ui/post/writing/PostWritingViewModelTest.kt, android/domain/src/main/java/com/teamtripdraw/android/domain/model/point/Point.kt, android/domain/src/main/java/com/teamtripdraw/android/domain/repository/PostRepository.kt
=> [feat] 감상 기록 / 감상 추가 요청과 함께 감상 기록 위치 추가를 하는 기능 추가 (#370)

android/app/src/main/java/com/teamtripdraw/android/data/httpClient/service/NaverGeocodingService.kt
- closed #525
- 네이버 api로부터 행정동만 받아오도록 수정하였습니다.
=> [refactor] 네이버 api로부터 행정동만 받아오도록 수정 (#525)

android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeFragment.kt, android/app/src/main/java/com/teamtripdraw/android/ui/home/HomeViewModel.kt
- closed #522 
- 통신 시간 관련 이슈 대응 (자세한 내용 이슈 참고)
=> [feat] 홈,감상 기록 / 감상 작성시 위치 저장하는 요구사항으로 변경 대응 (#522)

.gitignore, .gitmodules, backend/build.gradle
- closed #531 
서브모듈 사용 시 심각한 문제를 발견하고 이를 수정하려고 합니다.
- 서브모듈 디렉터리 이름 변경
- application.yml 내용 변경
- build.gradle 에서 copy 로직 삭제
무엇을 문제라고 보고 이를 어떻게 해결했는지 관련 [문서](https://github.com/woowacourse-teams/2023-trip-draw/discussions/533)를 남겨두었습니다.
=>  [refactor] 서브모듈 관련 설정 변경 - gradle copy 로직 제거 (#531)

backend/build.gradle, backend/src/main/java/dev/tripdraw/BackendApplication.java, backend/src/main/java/dev/tripdraw/area/application/AreaService.java, backend/src/main/java/dev/tripdraw/area/application/AreaServiceFacade.java, backend/src/main/java/dev/tripdraw/common/cache/CacheType.java, backend/src/main/java/dev/tripdraw/common/config/CacheConfig.java, backend/src/test/java/dev/tripdraw/area/application/AreaServiceTest.java
- closed #537 
- 지역 전체 조회에 대해 Caffeine 로컬 캐시를 적용했습니다.
[문서](https://github.com/woowacourse-teams/2023-trip-draw/discussions/538) 를 정리해두었습니다.
=> [refactor] 지역 전체 조회에 대한 로컬 캐시 적용 (#537)
