woowacourse-teams/2023-trip-draw

- android/app/src/main/java/com/teamtripdraw/android/di/RetrofitContainer.kt
- closed #66
- 리오의 좌충우동 성장기(서버 헤더 형식 이상하게 해서 고침)
> [fIx] 서버 인증 헤더 형식 변경 대응 인터셉터 작업 (#66)

- backend/src/main/java/dev/tripdraw/domain/post/Post.java
- backend/src/main/java/dev/tripdraw/domain/trip/Trip.java
- backend/src/main/java/dev/tripdraw/domain/trip/TripName.java
- backend/src/test/java/dev/tripdraw/domain/post/PostTest.java
- backend/src/test/java/dev/tripdraw/domain/trip/TripNameTest.java
- backend/src/test/java/dev/tripdraw/domain/trip/TripTest.java
- closed #79 
몹 프로그래밍으로 구현해서 리뷰없이 머지
3차 데모데이를 위한 도메인 추가 및 변경
```mermaid
classDiagram
Post --> Point
class Post {
Long tripId
}
class Point {
boolean hasPost
}
```
> [feat] 3차 데모데이를 위한 도메인 구현 (#79)

- backend/src/main/java/dev/tripdraw/application/TripService.java
- backend/src/main/java/dev/tripdraw/domain/trip/Status.java
- backend/src/main/java/dev/tripdraw/domain/trip/Trip.java
- backend/src/main/java/dev/tripdraw/domain/trip/TripStatus.java
- backend/src/main/java/dev/tripdraw/dto/trip/TripResponse.java
- backend/src/main/java/dev/tripdraw/presentation/controller/TripController.java
- backend/src/test/java/dev/tripdraw/application/MemberServiceTest.java
- backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
- backend/src/test/java/dev/tripdraw/domain/trip/TripTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/MemberControllerTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
- closed #87 
- 여행 단일 조회 api 및 테스트 추가했습니다.
- 여행 상태 관련 Enum Status 구현했습니다. (ONGOING, FINISHED)
- 여행에 상태를 나타내는 필드 Status status 추가했습니다.
> [feat] 여행 단일 조회 api 구현 및 여행 상태 필드(Enum) 추가 (#87)

- backend/src/main/java/dev/tripdraw/application/PostService.java
- backend/src/main/java/dev/tripdraw/domain/post/Post.java
- backend/src/main/java/dev/tripdraw/domain/post/PostRepository.java
- backend/src/main/java/dev/tripdraw/domain/trip/Point.java
- backend/src/main/java/dev/tripdraw/domain/trip/Route.java
- backend/src/main/java/dev/tripdraw/domain/trip/Trip.java
- backend/src/main/java/dev/tripdraw/dto/post/PostAndPointCreateRequest.java
- backend/src/main/java/dev/tripdraw/dto/post/PostPointCreateRequest.java
- backend/src/main/java/dev/tripdraw/dto/post/PostRequest.java
- backend/src/main/java/dev/tripdraw/dto/post/PostResponse.java
- backend/src/main/java/dev/tripdraw/dto/trip/PointCreateRequest.java
- backend/src/main/java/dev/tripdraw/dto/trip/PointResponse.java
- backend/src/main/java/dev/tripdraw/exception/trip/TripExceptionType.java
- backend/src/main/java/dev/tripdraw/presentation/controller/PostController.java
- backend/src/test/java/dev/tripdraw/application/PostServiceTest.java
- backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
- backend/src/test/java/dev/tripdraw/domain/trip/RouteTest.java
- backend/src/test/java/dev/tripdraw/domain/trip/TripTest.java
- backend/src/test/java/dev/tripdraw/dto/post/PostAndPointCreateRequestTest.java
- backend/src/test/java/dev/tripdraw/dto/post/PostPointCreateRequestTest.java
- backend/src/test/java/dev/tripdraw/dto/trip/PointCreateRequestTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java
- closed #72 
제목과 내용, 위치를 포함한 감상을 생성한다.
- 현재 위치에서 감상 생성 API 구현
- 사용자가 선택한 위치에서 감상 생성 API 구현
(* 사진 저장은 추후 추가 예정)
리뷰 부탁드립니다~
감사합니다!
> [feat] 감상 생성 API 구현 (#72)

- backend/src/main/java/dev/tripdraw/application/MemberService.java
- backend/src/main/java/dev/tripdraw/config/AuthConfig.java
- backend/src/main/java/dev/tripdraw/dto/member/MemberSearchResponse.java
- backend/src/main/java/dev/tripdraw/presentation/controller/MemberController.java
- backend/src/test/java/dev/tripdraw/application/MemberServiceTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/MemberControllerTest.java
- closed #105 
- 사용자 조회 기능을 추가했습니다.
- 기존의 사용자 생성 시 닉네임을 반환했는데 클라이언트에서 보낸 값 보다 조금 더 안정된 값을 필요로 하는 것 같습니다.
- 사실 사용자를 Id로 조회하는 것은 애매한 느낌이 들지만 지금은 이대로 가고 다른 인증 방식을 사용할 때 수정해보는건 어떨까 싶습니다.
> [feat] 회원 조회 기능 추가 (#105)

- backend/src/main/java/dev/tripdraw/application/PostService.java
- backend/src/main/java/dev/tripdraw/domain/post/Post.java
- backend/src/main/java/dev/tripdraw/dto/post/PostResponse.java
- backend/src/main/java/dev/tripdraw/exception/post/PostException.java
- backend/src/main/java/dev/tripdraw/exception/post/PostExceptionType.java
- backend/src/main/java/dev/tripdraw/presentation/controller/PostController.java
- backend/src/test/java/dev/tripdraw/application/PostServiceTest.java
- backend/src/test/java/dev/tripdraw/domain/post/PostTest.java
- backend/src/test/java/dev/tripdraw/dto/post/PostResponseAndPointCreateRequestTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/MemberControllerTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
- closed #73 
- 특정한 1개의 감상에 대한 모든 정보를 보여주는 API를 구현했습니다.
> [feat] 감상 상세 조회 API 구현 (#73)

- backend/src/main/java/dev/tripdraw/application/PostService.java
- backend/src/main/java/dev/tripdraw/domain/post/Post.java
- backend/src/main/java/dev/tripdraw/domain/post/PostRepository.java
- backend/src/main/java/dev/tripdraw/domain/trip/Point.java
- backend/src/main/java/dev/tripdraw/domain/trip/Trip.java
- backend/src/main/java/dev/tripdraw/dto/post/PostsResponse.java
- backend/src/main/java/dev/tripdraw/exception/post/PostExceptionType.java
- backend/src/main/java/dev/tripdraw/exception/trip/TripExceptionType.java
- backend/src/main/java/dev/tripdraw/presentation/controller/PostController.java
- backend/src/test/java/dev/tripdraw/application/PostServiceTest.java
- backend/src/test/java/dev/tripdraw/domain/post/PostTest.java
- backend/src/test/java/dev/tripdraw/domain/trip/PointTest.java
- backend/src/test/java/dev/tripdraw/domain/trip/TripTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java
- closed #74
- closed #147 
- 특정 여행의 모든 감상 조회 API 구현
- 감상 생성 시, 감상에 속한 위치의 hasPost 필드 true로 변경
작업 시간 탓에, 부득이 하게 2개의 issue를 한 번에 해결했습니다.
양해 부탁드립니다.
감사합니다!
> [feat] 특정 여행의 모든 감상 조회 API 구현 (#74)

- backend/src/main/java/dev/tripdraw/dto/trip/TripResponse.java
- backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
- closed #176 
- 여행 단일 조회 필드명 routes에서 route로 변경
> [fix] 여행 단일 조회 필드명 routes에서 route로 변경 (#176)

- backend/src/main/java/dev/tripdraw/application/PostService.java
- backend/src/test/java/dev/tripdraw/application/PostServiceTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/PostControllerTest.java
- closed #194 
- 감상 목록 정렬되지 않는 문제 해결
- 위치의 recordedAt 필드의 역순으로 정렬
- rebase과정에서 삭제되었던 테스트 복구
> [fix] 감상 목록 정렬 (#194)

- backend/src/main/java/dev/tripdraw/domain/trip/Trip.java
- backend/src/test/java/dev/tripdraw/domain/trip/TripTest.java
- closed #221 
- 삭제된 위치 정보가 조회되지 않도록 수정했습니다.
> [fix] 삭제된 위치 정보가 조회되지 않도록 수정 (#221)

- backend/src/main/java/dev/tripdraw/application/PostService.java
- closed #249 
- As-is : 감상 수정 시, multipart/form-data의 file 필드를 넣지 않으면, 기존에 저장된 이미지가 null로 변환됨
- To-be : 감상 수정 시, multipart/form-data의 file 필드를 넣지 않으면, 기존에 저장된 이미지가 그대로 유지됨
> [fix] 수정하지 않은 감상의 이미지 그대로 유지 (#249)

- backend/src/main/java/dev/tripdraw/domain/trip/Trip.java
- backend/src/main/java/dev/tripdraw/dto/trip/TripSearchResponse.java
- backend/src/test/java/dev/tripdraw/application/TripServiceTest.java
- backend/src/test/java/dev/tripdraw/dto/trip/TripSearchResponseTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
- closed #251 
- 모든 여행 조회의 응답을 수정합니다.
- Trip 생성자에서 imageUrl, routeImageUrl을 빈값으로 초기화할 수 있도록 수정합니다.
> [refactor] 모든 여행 조회 응답 수정 (#251)

- backend/src/main/java/dev/tripdraw/config/swagger/MultipartJackson2HttpMessageConverter.java
- backend/src/main/java/dev/tripdraw/presentation/controller/PostController.java
- closed #253 
- 현재 위치의 감상 생성 API
- 사용자가 선택한 위치의 감상 생성 API
- 감상 수정 API
- Swagger에서 multipart를 입력하는 API 테스트 시 발생하는 문제를 해결하기 위한 것으로, Postman 또는 클라이언트의 일반 호출에서는 해당 타입이 사용되지 않습니다.
> [docs] Swagger를 고도화한다 (#253)

- android/app/build.gradle.kts
- android/build.gradle.kts
- android/gradle/libs.versions.toml
- closed #258 
- 버그 리포팅을 위한 Firebase Crashlytics를 연결한다
- GA또한 로깅시스템을 위해 연결한다
- 슬랙을 연결하여 빠르게 버그리포팅을 한다.
> [feat] Firebase Crashlytics 연결 (#258)

- android/app/src/main/java/com/teamtripdraw/android/ui/common/bindingAdapter/TripTitleDialogBindingAdapter.kt
- android/app/src/main/java/com/teamtripdraw/android/ui/common/dialog/SetTripTitleDialog.kt
- android/app/src/main/java/com/teamtripdraw/android/ui/common/dialog/SetTripTitleDialogViewModel.kt
- android/app/src/main/java/com/teamtripdraw/android/ui/history/HistoryFragment.kt
- android/app/src/main/java/com/teamtripdraw/android/ui/history/detail/HistoryDetailActivity.kt
- android/app/src/main/java/com/teamtripdraw/android/ui/history/detail/HistoryDetailViewModel.kt
- android/app/src/main/java/com/teamtripdraw/android/ui/home/markerSelectedBottomSheet/MarkerSelectedBottomSheet.kt
- android/app/src/main/java/com/teamtripdraw/android/ui/model/mapper/TripUiMapper.kt
- android/app/src/main/res/drawable/shape_td_gray_fill_5_rect.xml
- android/app/src/main/res/layout/fragment_trip_title_dialog.xml
- closed #262 
- 여행 히스토리 상세 화면에서 여행 제목 수정 기능
- 제목 수정 후 화면 이동 혹은 화면 업데이트 작업
- 제목 수정 다이얼로그 버튼 활성/비활성 기능
> [feat] 여행 히스토리 / 여행 제목 수정 기능 (#262)

- backend/build.gradle
- backend/src/main/java/dev/tripdraw/application/MemberService.java
- backend/src/main/java/dev/tripdraw/application/TripService.java
- backend/src/main/java/dev/tripdraw/config/AuthConfig.java
- backend/src/main/java/dev/tripdraw/config/swagger/MultipartJackson2HttpMessageConverter.java
- backend/src/main/java/dev/tripdraw/config/swagger/SwaggerConfig.java
- backend/src/main/java/dev/tripdraw/domain/member/Member.java
- backend/src/main/java/dev/tripdraw/domain/post/PostRepository.java
- backend/src/main/java/dev/tripdraw/domain/trip/Point.java
- backend/src/main/java/dev/tripdraw/domain/trip/Route.java
- backend/src/main/java/dev/tripdraw/domain/trip/TripRepository.java
- backend/src/main/java/dev/tripdraw/dto/member/MemberSearchResponse.java
- backend/src/main/java/dev/tripdraw/exception/trip/TripExceptionType.java
- backend/src/main/java/dev/tripdraw/presentation/controller/PostController.java
- backend/src/main/java/dev/tripdraw/presentation/controller/TripController.java
- backend/src/main/resources/application-local.yml
- backend/src/main/resources/db/migration/h2/V6__modifyMemberAndAddTripDeletion.sql
- backend/src/main/resources/db/migration/mysql/V6__modifyMemberAndAddTripDeletion.sql
- backend/src/test/java/dev/tripdraw/application/MemberServiceTest.java
- backend/src/test/java/dev/tripdraw/domain/member/MemberRepositoryTest.java
- backend/src/test/java/dev/tripdraw/domain/member/MemberTest.java
- backend/src/test/java/dev/tripdraw/domain/post/PostRepositoryTest.java
- backend/src/test/java/dev/tripdraw/domain/trip/TripRepositoryTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/MemberControllerTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/TripControllerTest.java
- closed #255 
- 여행 삭제 기능 추가
- 회원 탈퇴 기능 수정
- 위치 삭제 기능 수정
저희의 개인정보 처리방침에 따르면 회원 탈퇴 요청 시 개인정보를 파기해야 합니다. 따라서 soft delete 를 적용하기에 애매합니다. 앱 심사를 앞두고 있으므로 보수적으로 코드를 작성했습니다.
회원 탈퇴 시, 회원의 여행, 감상 등의 데이터가 물리적으로 삭제되어야 합니다.(hard delete) 따라서 회원의 일반적인 여행 삭제 요청에 대해서는 soft delete를 하고, 회원 탈퇴의 경우에만 hard delete를 하는 방법을 구상했습니다. 이를 구현하기 위해 여러가지 시도를 해보았으나 현재의 구조에서는 어렵다는 결론을 내렸습니다. 가장 간단한 방법인 hard delete를 채택했습니다.
- 위치 정보 삭제 역시 hard delete 고려 중입니다. 다른 엔티티와 통일성을 맞추기 위함입니다.
- 이전의 코드에서, 위치 정보를 삭제한 후 여행의 경로를 조회하면 삭제된 위치도 함께 조회됩니다.
- 위치 정보 삭제 후, 삭제된 위치가 조회되지 않도록 수정했습니다.
> [feat] 여행 삭제 기능 추가 및 회원 탈퇴 기능 수정 (#255)

- backend/src/main/java/dev/tripdraw/application/AuthService.java
- backend/src/main/java/dev/tripdraw/application/oauth/AuthTokenManager.java
- backend/src/main/java/dev/tripdraw/config/swagger/SwaggerConfig.java
- backend/src/main/java/dev/tripdraw/domain/member/MemberRepository.java
- backend/src/main/java/dev/tripdraw/dto/auth/OauthRequest.java
- backend/src/main/java/dev/tripdraw/dto/auth/OauthResponse.java
- backend/src/main/java/dev/tripdraw/dto/auth/RegisterRequest.java
- backend/src/main/java/dev/tripdraw/exception/member/MemberExceptionType.java
- backend/src/main/java/dev/tripdraw/presentation/controller/AuthController.java
- backend/src/test/java/dev/tripdraw/application/AuthServiceTest.java
- backend/src/test/java/dev/tripdraw/domain/member/MemberRepositoryTest.java
- backend/src/test/java/dev/tripdraw/presentation/controller/AuthControllerTest.java
- closed #278 
- 회원 닉네임 등록 시 중복 검증을 추가했습니다.
두 가지 선택지를 고려했습니다.
1. 전체 회원의 이름 목록을 불러와서 Member.changeName() 메서드의 파라미터로 전달한 후, Member.changeName() 메서드 내에서 검증하는 방법
2. MemberRepository.existsByNickname()  메서드로 존재 여부만 확인한 후 검증하는 방법
이 중에 첫번째 방법은 회원의 수가 많아질수록 "데이터 조회 시간" + "중복 검사 시간"이 늘어날 것으로 예상했습니다. 따라서 두 번째 방법을 택했습니다. 자세한 내용은 아래와 같습니다.
memberRepository에 `existsByNickname` 메서드를 추가했습니다.
```java
public interface MemberRepository extends JpaRepository<Member, Long> {
boolean existsByNickname(String nickname);
}
```
authService에서 이 메서드를 활용합니다.
```java
@Transactional
@Service
public class AuthService {
// (...)
public OauthResponse register(RegisterRequest registerRequest) {
OauthClient oauthClient = oauthClientProvider.provide(registerRequest.oauthType());
OauthInfo oauthInfo = …
```
> [feat] 회원 닉네임 등록 시 중복 검증 추가 (#278)

- android/.gitignore
- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/java/com/teamtripdraw/android/TripDrawApplication.kt
- android/app/src/main/java/com/teamtripdraw/android/data/httpClient/retrofitAdapter/ResponseState.kt
- android/build.gradle.kts
- android/gradle/libs.versions.toml
- android/support/build.gradle.kts
- android/support/src/debug/java/CrashlyticsHandlerImpl.kt
- android/support/src/main/java/com/teamtripdraw/android/support/framework/presentation/log/LogUtil.kt
- android/support/src/main/java/com/teamtripdraw/android/support/framework/presentation/log/TripDrawLogUtil.kt
- android/support/src/main/java/com/teamtripdraw/android/support/framework/presentation/log/tripDrawLogUtil/CrashlyticsHandler.kt
- android/support/src/main/java/com/teamtripdraw/android/support/framework/presentation/log/tripDrawLogUtil/TripDrawLogUtil.kt
- android/support/src/release/java/CrashlyticsHandlerImpl.kt
- closed #310 
- 방학동안 원격로깅 툴 연결하고 로그유틸 만들어봤습니다.
이에 대한 일대기는 블로그와 이슈에 열심히 남겨두었으니 두개 참고하셔서 학습하시고 사용하시길 바랍니다!!!!
[멧돼지의 파워블로그](https://mccoy-devloper.tistory.com/131)
시간나실때 본인 부분 Log찍어야 했던 것 다 Logutil의 genral 로 변경해주시면됩니다
> [feat] 로그 유틸 생성 Sentry (#310)

- backend/src/main/java/dev/tripdraw/file/application/FilePath.java
- backend/src/main/java/dev/tripdraw/file/application/FileUploader.java
- backend/src/main/java/dev/tripdraw/file/domain/FileType.java
- backend/src/main/java/dev/tripdraw/post/application/PostService.java
- backend/src/main/java/dev/tripdraw/post/dto/PostAndPointCreateRequest.java
- backend/src/main/java/dev/tripdraw/trip/domain/Point.java
- backend/src/test/java/dev/tripdraw/file/application/FileUploaderTest.java
- backend/src/test/java/dev/tripdraw/post/application/PostServiceTest.java
- closed #341 
- 여행 이미지에 대한 기본 값을 지정하는 기능을 추가했습니다.
- 이미지를 저장하는 경우 제일 마지막으로 저장된 이미지를 여행의 기본 이미지로 설정하였습니다.
- PostService의 읽기 전용 메서드에 Transactional readOnly를 추가하였습니다.
- 파일 타입을 FileUpload 내부에서 가져오도록 했습니다.
> [feat] 여행 이미지에 대한 기본 값 지정하는 기능 추가 (#341)

- backend/src/main/java/dev/tripdraw/post/dto/PostResponse.java
- backend/src/main/java/dev/tripdraw/trip/dto/TripResponse.java
- backend/src/main/java/dev/tripdraw/trip/dto/TripSearchResponse.java
- backend/src/test/java/dev/tripdraw/post/presentation/PostControllerTest.java
- closed #343 
- 이미지가 null인 경우 빈 문자열을 반환하도록 수정했습니다.
- routeImageUrl에 imageUrl을 반환하는 부분을 수정했스빈다.
> [fix] dto의 image null인 경우 빈 문자열을 반환하도록 수정 (#343)

- backend/src/main/java/dev/tripdraw/auth/application/AuthFacadeService.java
- backend/src/main/java/dev/tripdraw/auth/application/AuthService.java
- backend/src/main/java/dev/tripdraw/auth/application/OAuthService.java
- backend/src/main/java/dev/tripdraw/auth/application/TokenGenerateService.java
- backend/src/main/java/dev/tripdraw/auth/config/RefreshTokenConfig.java
- backend/src/main/java/dev/tripdraw/auth/domain/RefreshToken.java
- backend/src/main/java/dev/tripdraw/auth/presentation/AuthController.java
- backend/src/main/java/dev/tripdraw/common/config/AuthConfig.java
- backend/src/main/java/dev/tripdraw/member/application/MemberService.java
- backend/src/main/java/dev/tripdraw/member/presentation/MemberController.java
- backend/src/test/java/dev/tripdraw/auth/application/AuthFacadeServiceTest.java
- backend/src/test/java/dev/tripdraw/auth/application/AuthServiceTest.java
- backend/src/test/java/dev/tripdraw/auth/application/OAuthServiceTest.java
- backend/src/test/java/dev/tripdraw/auth/application/TokenGenerateServiceTest.java
- backend/src/test/java/dev/tripdraw/member/application/MemberServiceTest.java
- backend/src/test/java/dev/tripdraw/member/presentation/MemberControllerTest.java
- backend/src/test/java/dev/tripdraw/test/fixture/MemberFixture.java
- closed #349 
- OAuth API 호출에 해당하는 부분을 Facade를 이용해서 트랜잭션에서 제외했습니다.
다음과 같은 구조로 되어있습니다.
```mermaid
graph LR
A[AuthFacadeService] --> OAuthService
A --> AuthService
A --> TokenGenerateService
```
로그인 후 토큰 발급까지는 Transaction으로 묶어야 해서, TransactionTemplate을 사용했습니다.
> [refactor] OAuth API 호출에 해당하는 부분을 트랜잭션에서 제외 (#349)

- backend/src/main/java/dev/tripdraw/post/application/PostService.java
- backend/src/main/java/dev/tripdraw/post/dto/PostSearchRequest.java
- backend/src/main/java/dev/tripdraw/post/presentation/PostController.java
- backend/src/main/java/dev/tripdraw/trip/application/TripService.java
- backend/src/main/java/dev/tripdraw/trip/dto/TripSearchRequest.java
- backend/src/main/java/dev/tripdraw/trip/presentation/TripController.java
- backend/src/test/java/dev/tripdraw/post/application/PostServiceTest.java
- backend/src/test/java/dev/tripdraw/post/presentation/PostControllerTest.java
- backend/src/test/java/dev/tripdraw/test/fixture/TripSearchQueryParamsFixture.java
- backend/src/test/java/dev/tripdraw/trip/acceptance/TripSearchAcceptanceTest.java
- backend/src/test/java/dev/tripdraw/trip/application/TripServiceTest.java
- backend/src/test/java/dev/tripdraw/trip/presentation/TripControllerTest.java
- closed #379 
- Get 요청 시 body가 아닌 QueryString으로 데이터를 보내도록 변경합니다.
- Post 전체 조회 변경
- Trip 전체 조회 변경
> [refactor] Get 요청 시 body 제거 (#379)

- backend/src/main/java/dev/tripdraw/post/application/PostService.java
- backend/src/main/java/dev/tripdraw/post/presentation/PostController.java
- backend/src/test/java/dev/tripdraw/post/application/PostServiceTest.java
- closed #388 
- 감상 조회시 다른 유저도 감상을 조회할 수 있도록 변경했습니다.
- 현재 인증을 위해서, PostController에서 감상을 조회하는 기능이 포함된 메서드들의 파라미터로 `@Auth LoginUser loginUser`가 남아있습니다.
> [feat] 감상 조회시 다른 유저도 감상을 조회할 수 있도록 변경 (#388)

- backend/src/main/java/dev/tripdraw/post/domain/PostRepository.java
- backend/src/main/java/dev/tripdraw/post/query/PostCustomRepositoryImpl.java
- backend/src/main/java/dev/tripdraw/trip/domain/Point.java
- closed #387 
- 감상 조회시 N+1문제가 있었습니다.
- Fetch Join으로 해결했습니다.
- 추가로, 전체 감상 조회시 trip을 다시 조회하는 경우가 있었습니다.
- 그래서 trip도 fetch join했습니다.
> [refactor] 감상 조회시 N+1 문제 해결

- backend/src/main/java/dev/tripdraw/common/async/AsyncConfigurationProperties.java
- backend/src/main/java/dev/tripdraw/common/async/AsyncExceptionHandler.java
- backend/src/main/java/dev/tripdraw/common/async/MdcTaskDecorator.java
- backend/src/main/java/dev/tripdraw/common/config/AsyncConfig.java
- backend/src/main/resources/application-local.yml
- closed #368 
현재 경로 이미지 생성 기능은 비동기로 처리되고 있습니다.
로그를 확인하는 도중 `@Async`가 적용된 메서드에서 예외가 발생하는 경우 로그가 정상적으로 출력되지 않는 문제를 확인했습니다.
확인해보니 Spring의 `@ControllerAdvice` + `@ExceptionHandler`의 경우 동기 예외만 처리해주고, 비동기 예외를 처리해주지 않았습니다.
따라서 Spring에서 지원해주는 AsyncUncaughtExceptionHandler 인터페이스를 구현해서 예외를 처리해주는 클래스를 생성하였습니다.
```java
@Slf4j
public class AsyncExceptionHandler implements AsyncUncaughtExceptionHandler {
private static final String LOG_FORMAT = "[%s] %s";
@Override
public void handleUncaughtException(Throwable throwable, Method method, Object... obj) {
log.info(String.format(LOG_FORMAT, MDC.get(REQUEST_ID.key()), throwable.getMessage()), throwable);
}
}
```
해당 AsyncExceptionHandler의 경우 AsyncConfigurer를 구현한 Configuration 클래스를 사용하여 등록할 수 있습니다.
getAsyncUncaughtExceptionHandler 메서드를 오버라이딩하여 이전에 생성해준 …
> [feat] 비동기 예외 처리 기능 추가 (#368)

- backend/src/main/java/dev/tripdraw/common/async/AsyncConfigurationProperties.java
- backend/src/main/java/dev/tripdraw/common/async/AsyncExceptionHandler.java
- backend/src/main/java/dev/tripdraw/common/async/MdcTaskDecorator.java
- backend/src/main/java/dev/tripdraw/common/config/AsyncConfig.java
- backend/src/main/java/dev/tripdraw/draw/application/RouteImageGenerator.java
- backend/src/main/java/dev/tripdraw/post/domain/PostRepository.java
- backend/src/main/java/dev/tripdraw/trip/application/TripDeleteEventHandler.java
- backend/src/main/java/dev/tripdraw/trip/domain/PointRepository.java
- backend/src/main/java/dev/tripdraw/trip/domain/TripRepository.java
- backend/src/main/resources/application-local.yml
- backend/src/test/java/dev/tripdraw/member/application/MemberServiceTest.java
- backend/src/test/java/dev/tripdraw/post/domain/PostRepositoryTest.java
- backend/src/test/java/dev/tripdraw/trip/application/TripDeleteEventHandlerTest.java
- backend/src/test/java/dev/tripdraw/trip/domain/PointRepositoryTest.java
- backend/src/test/java/dev/tripdraw/trip/domain/TripRepositoryTest.java
- closed #398 
- 회원 삭제 시 쿼리가 19000 여개 나가는 것을 보고 깜짝 놀래서 바꿔보았습니다.
관련 문서 : https://github.com/woowacourse-teams/2023-trip-draw/discussions/402
> [refactor] 회원 삭제 시 쿼리 변경 (#398)

- backend/src/main/java/dev/tripdraw/common/config/AuthConfig.java
- backend/src/main/java/dev/tripdraw/post/application/PostService.java
- backend/src/main/java/dev/tripdraw/post/domain/PostRepository.java
- backend/src/main/java/dev/tripdraw/post/presentation/PostController.java
- backend/src/test/java/dev/tripdraw/post/application/PostServiceTest.java
- backend/src/test/java/dev/tripdraw/post/domain/PostRepositoryTest.java
- backend/src/test/java/dev/tripdraw/post/presentation/PostControllerTest.java
- closed #461 
- point Id를 통해 post를 조회하는 api 를 추가했습니다.
- endpoint를 `/points/{pointId}/post` 로 설정했습니다. 혹시 더 나은 방안이 떠오르신다면 추천 부탁드립니다.
- 해당 기능에 인가 처리가 필요하지 않다고 판단했습니다. 기획 상 누구나 다른 사람의 위치정보를 눌러 감상 기록을 조회할 수 있어야 하기 때문입니다. 따라서 AuthConfig의 excludePathPatterns 설정으로 Interceptor가 해당 Url에서 작동하지 않도록 했습니다. 더 나은 방안을 알고 계신다면 알려주세요. 공부하겠습니다!
> [feat] point Id를 통해 post를 조회하는 api (#461)

- backend/src/main/java/dev/tripdraw/common/config/AuthConfig.java
- backend/src/main/java/dev/tripdraw/post/application/PostService.java
- backend/src/main/java/dev/tripdraw/post/domain/PostRepository.java
- backend/src/main/java/dev/tripdraw/post/dto/PostSearchResponse.java
- backend/src/main/java/dev/tripdraw/post/presentation/PostController.java
- backend/src/main/java/dev/tripdraw/trip/application/TripService.java
- backend/src/main/java/dev/tripdraw/trip/dto/TripSearchResponse.java
- backend/src/main/java/dev/tripdraw/trip/dto/TripsSearchResponse.java
- backend/src/test/java/dev/tripdraw/post/application/PostServiceTest.java
- backend/src/test/java/dev/tripdraw/post/domain/PostRepositoryTest.java
- backend/src/test/java/dev/tripdraw/post/presentation/PostControllerTest.java
- backend/src/test/java/dev/tripdraw/trip/application/TripServiceTest.java
- backend/src/test/java/dev/tripdraw/trip/presentation/TripControllerTest.java
- closed #463 
- 여행 전체 조회 시 memberNickname 을 함께 반환하도록 수정
- 감상 전체 조회 시 memberNickname 을 함께 반환하도록 수정
Trip, Post 모두 memberId를 필드로 갖고 있습니다. 따라서 MemberRepository에서 memberId로 nickname을 조회해서 반환 dto에 포함하도록 변경했습니다.
이것이 바뀐 코드입니다.
```java
@Transactional(readOnly = true)
public TripsSearchResponse readAll(TripSearchRequest tripSearchRequest) {
TripSearchConditions condition = tripSearchRequest.toTripSearchConditions();
TripPaging tripPaging = tripSearchRequest.toTripPaging();
List<Trip> trips = tripQueryService.readAllByQueryConditions(condition, tripPaging);
List<TripSearchResponse> responses = trips.stream()
.map(trip -> TripSearchResponse.from(trip, memberRepository.getNicknameById(trip.memberId())))
.toList();
if (tripPaging.hasNextPage(responses.size())) {
return …
```
> [refactor] 여행, 감상 전체 조회 시 각각 게시글 회원의 닉네임을 함께 반환하도록 수정 (#463)

- .gitignore
- backend/src/main/java/dev/tripdraw/admin/application/AdminService.java
- backend/src/main/java/dev/tripdraw/post/application/PostQueryService.java
- backend/src/main/java/dev/tripdraw/post/application/PostService.java
- backend/src/main/java/dev/tripdraw/post/dto/PostPaging.java
- backend/src/main/java/dev/tripdraw/post/dto/PostSearchPaging.java
- backend/src/main/java/dev/tripdraw/post/dto/PostSearchRequest.java
- backend/src/main/java/dev/tripdraw/post/query/PostCustomRepository.java
- backend/src/main/java/dev/tripdraw/post/query/PostCustomRepositoryImpl.java
- backend/src/main/java/dev/tripdraw/trip/application/TripQueryService.java
- backend/src/main/java/dev/tripdraw/trip/application/TripService.java
- backend/src/main/java/dev/tripdraw/trip/dto/TripSearchPaging.java
- backend/src/main/java/dev/tripdraw/trip/query/TripPaging.java
- backend/src/test/java/dev/tripdraw/common/domain/TripPagingTest.java
- backend/src/test/java/dev/tripdraw/post/domain/PostCustomRepositoryImplTest.java
- backend/src/test/java/dev/tripdraw/post/dto/PostPagingTest.java
- backend/src/test/java/dev/tripdraw/trip/application/TripQueryServiceTest.java
- closed #473 
- 서버 nginx 에서 QueryString 처리하지 못하는 문제 해결 (feat. 리오)
- Paging 에서 limit이 null 인 경우 default 값 설정
- 감상과 여행 Paging 관련 컨벤션 맞추기
- gitignore 에 private file 추가
limit이 null 인 경우, 예외를 던지기보다는 default 값으로 설정하는 것이 나을 것이라 판단했습니다.
default 값은 지금 팀 컨벤션인 `limit = 20` 으로 설정했습니다.
> [fix] Paging 처리 시 NullPointerException 예외 처리 (#473)

- android/app/src/main/java/com/teamtripdraw/android/ui/common/dialog/DialogUtil.kt
- android/app/src/main/java/com/teamtripdraw/android/ui/common/dialog/ResponsiveUiDialogSizeAdjuster.kt
- android/app/src/main/java/com/teamtripdraw/android/ui/common/dialog/SetTripTitleDialog.kt
- closed #466 
- 다이얼로스 태블릿 사이즈 조정 (자세한사항 이슈 참고)
태블릿
폰
> [feat] 다이얼로그 태블릿 대응 사이즈 조정 (#466)

- android/app/src/main/res/layout/activity_post_writing.xml
- android/app/src/main/res/values-w600dp/dimens.xml
- android/app/src/main/res/values/dimens.xml
- closed #506
- 태블릿 화면에서 이미지 미리보기 크기 조절
> [feat] 감상 작성 / 태블릿 화면에서 이미지 미리보기 크기 조절 (#506)
